version: "3.8"
{%- set u = cookiecutter.lname.upper() %}
{%- set is_mysql = 'mysql' in cookiecutter.db_image or 'maria' in cookiecutter.db_image %}
{%- set network = '{}_NETWORK'.format(u).replace('-', '_') %}
{%- set netpref2 = cookiecutter.network.split('.')[:2]|join('.') %}
{%- set netpref3 = cookiecutter.network.split('.')[:3]|join('.') %}
{%- macro addlog(service) %}
{%- if cookiecutter.with_logging %}
    logging: {driver: syslog, options: {tag: "{{service}}", syslog-address: "tcp://${LOGGING_EXT_IP:-127.0.0.1}:${LOGGING_EXT_PORT:-{{cookiecutter.log_port}}}"}}
{%- endif %}
{%- endmacro %}
x-bases:
  x-env: &env
    env_file: [.env]
    environment: &env_env
      BASE_IMAGE: "${BASE_IMAGE:-{{cookiecutter.base_image}}}"
      NGINX_REAL_IP_FROM: "10.0.0.0/8 192.168.0.0/16 172.16.0.0/12{% if cookiecutter.network%} {{'${'}}{{network}}:-{{netpref3}}.0/12}{%endif%}"
{%- if cookiecutter.db_image %}
{%- if 'post' in cookiecutter.db_image %}
      PGPASSWD: "${PGPASSWD:-db}"
      PGPASSWORD: "${PGPASSWD:-db}"
      POSTGRES_DB: db
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: db
      POSTGRES_PORT: '5432'
      POSTGRES_USER: db
{%- elif is_mysql %}
      MYSQL_HOST: "${MYSQL_HOST:-db}"
      MYSQL_PORT: "${MYSQL_PORT:-3306}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-db}"
      MYSQL_USER: "${MYSQL_USER:-user}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-password}"
      MYSQL_PWD: "${MYSQL_PASSWORD:-password}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD:-password}"
{%- endif %}
{%- endif %}
  x-base: &base
    <<: [ *env ]
{%- if cookiecutter.network %}
networks: {app_net: {driver: bridge, ipam: {config: [{subnet: "{{'${'}}{{network}}:-{{netpref3}}.0/24}"}], driver: default}}}
{%- endif %}
services:
{%- if cookiecutter.with_logging %}
  log:
    image: "{{cookiecutter.rsyslog_image}}"
    logging: {driver: "json-file", options: {max-size: "10M", max-file: "50"}}
    ports: ["${LOGGING_EXT_IP:-127.0.0.1}:${LOGGING_EXT_PORT:-{{cookiecutter.log_port}}}:10514"]
{%- if cookiecutter.network %}
    networks: {app_net: {ipv4_address: "{{'${'}}{{network}}:-{{netpref3}}}.${SYSLOG_IP_ADDRESS:-252}"}}
{%- endif %}
{%- endif %}
  app:
    <<: [ *base ]
    depends_on: [setup{% if cookiecutter.with_logging%}, log{%endif%}]
    image: "${DOCKER_IMAGE:-{{cookiecutter.docker_image}}}"
{{-addlog("app")}}
    environment:
      <<: [ *env_env ]
      START_COMMAND: "${START_COMMAND:-}"
    volumes:
    - "${DATA_FOLDER:-./data}:/w/data"
    - helpers:/helpers:rw
{%- if cookiecutter.network %}
    networks: {app_net: {ipv4_address: "{{'${'}}{{network}}:-{{netpref3}}}.${APP_IP_ADDRESS:-2}"}}
{%- endif %}
    entrypoint:
    - bash
    - -ec
    - |-
      if [[ -n $${SDEBUG-} ]];then set -x;fi
      export PATH=/helpers:$$PATH
      while ! ( for i in dockerize frep;do $$i --version||exit 1;done; );do sleep 0.5;done >/dev/null 2>&1
      dockerize -wait http://setup -timeout 60s &>/dev/null
      while read f;do d=/$$(dirname $$f)/$$(basename sys/$$f .frep);echo "Generating $$f" >&2;frep "sys/$$f:$$d" --overwrite;done < <(cd sys && find -type f -name "*frep")
      exec docker-entrypoint.sh "$$@"
{%- if cookiecutter.db_image %}
  db:
    <<: [ *base ]
    depends_on: [{% if cookiecutter.with_logging%}log{%endif%}]
    image: {{cookiecutter.db_image}}
{{- addlog("db")}}
{%- if cookiecutter.network %}
    networks: {app_net: {ipv4_address: "{{'${'}}{{network}}:-{{netpref3}}}.${DB_IP_ADDRESS:-4}"}}
{%- endif %}
    security_opt: [seccomp=unconfined]
    volumes:
{%- if 'post' in cookiecutter.db_image %}
    - db:/var/lib/postgresql/data:rw
{%- elif is_mysql %}
    - db:/var/lib/mysql:rw
{%- endif %}
{%- endif %}
{%- set depends = [] %}
{%- if cookiecutter.with_logging%}{% set _ = depends.append('log') %}{%endif %}
{%- if cookiecutter.db_image%}{% set _ = depends.append('db') %}{%endif %}
  setup:
    depends_on: {{depends}}
    image: "${SETUP_IMAGE:-{{cookiecutter.db_image and cookiecutter.db_image or cookiecutter.corpusops_image}}}"
    <<: [ *base ]
    entrypoint:
    - bash
    - -ec
    - |-
      cp -arvf /cops_helpers/* /helpers
      export PATH=/cops_helpers:/$$PATH
      hf=/started_hr
      HELPERS_TIMEOUT=$${HELPERS_TIMEOUT:-45s}
      {% if cookiecutter.db_image %}
      f=/started_$$(echo $$POSTGRES_DB|sed -re "s![/:]!__!g")
      {% endif %}
      rf() { for fl in{%if cookiecutter.db_image %} $$f{% endif %} $$hf;do if [ -f $$fl ] ;then rm -f $$fl;fi;done; }
      echo "Try helpers availability" >&2
      ( set +ex;while true;do /helpers/frep --version && touch $$hf&&break;sleep 1;echo retryh;done; )&
      rf
{%- if cookiecutter.db_image %}
      DB_STARTUP_TIMEOUT=$${DB_STARTUP_TIMEOUT:-45s}
{%- if 'post' in cookiecutter.db_image %}
      u="postgres://$$POSTGRES_USER:$$POSTGRES_PASSWORD@$$POSTGRES_HOST:$$POSTGRES_PORT/$$POSTGRES_DB"
      echo "Try connection to pgsql: $$POSTGRES_DB & wait for db init" >&2
      ( while true;do if ( echo select 1|psql -v ON_ERROR_STOP=1 $$u; );then touch $$f&&break;fi;done )&
{%- elif is_mysql %}
      echo "Try connection to mysql: $$MYSQL_DATABASE & wait for db init" >&2
      ( while true;do if ( echo select 1|mysql $$MYSQL_DATABASE; );then touch $$f&&break;fi;done )&
{%- endif %}
      dockerize -timeout 300s -wait "file:///$$f"
{%- endif%}
      set -x
      dockerize -timeout 900s -wait "file:///$$hf"
      set +x
      rf
      while true;do printf "HTTP/1.1 200 OK\nContent-Length: 7\n\nstarted\n"|( nc -l -p 80 || /bin/true);done
{{-addlog("setup")}}
{%- if cookiecutter.network %}
    networks: {app_net: {ipv4_address: "{{'${'}}{{network}}:-{{netpref3}}}.${SETUP_IP_ADDRESS:-6}"}}
{%- endif %}
    volumes:
    - helpers:/helpers:rw
volumes:
  helpers: {}
{%- if cookiecutter.db_image %}
  db:
{%- endif %}
