version: "3.8"
x-images:
  noop: &noop
    depends_on: []
    <<: [ *env ]
    image: "${DOCKER_IMAGE:-{{cookiecutter.docker_image}}}"
    command: []
    entrypoint: [sh, -c 'while :;do sleep 50000;done']
services:
  log: {<<: [ *noop ]}
  app:
    environment:
      NO_NVM_INSTALL: "${NO_NVM_INSTALL-}"
      NO_PIP_INSTALL: "${NO_PIP_INSTALL-}"
      FILES_EXTRA_DIRS: "${DATA_FOLDER:-./data} ./.tox"
    volumes:
    - "./apt.txt:/w/apt.txt"
    - "${DATA_FOLDER:-./data}:/w/data"
    - "./bin:/w/bin"
    - "./.git:/w/.git"
    - "./sys:/w/sys"
{%- if cookiecutter.with_pyapp %}
    - "./requirements:/w/requirements"
    - "./lib:/w/lib"
    - "./src:/w/src"
    - "./setup.py:/w/setup.py"
    - "./setup.cfg:/w/setup.cfg"
    - "./setup.cfg:/w/tox.ini"
{%- endif %}
{%- if cookiecutter.with_node %}
    - "./node_modules:/w/node_modules"
    - "./.nvmrc:/w/.nvmrc"
{%- endif%}
