version: "3.8"
{%- set u = cookiecutter.lname.upper() %}
{%- set network = '{}_NETWORK'.format(u) %}
x-bases:
  x-base: &base
    env_file: [.env]
    environment:
      TEST_MODE: "1"
      {% if cookiecutter.with_mailcatcher -%}
      MAILCATCHER_PASSWORD: secret
      MAILCATCHER_USER: mailcatcher
      MH_API_BIND_ADDR: 0.0.0.0:8025
      MH_AUTH_FILE: /home/mailhog/pw
      MH_MAILDIR_PATH: /mails
      MH_SMTP_BIND_ADDR: 0.0.0.0:1025
      MH_STORAGE: maildir
      MH_UI_BIND_ADDR: 0.0.0.0:8025
      MH_UI_WEB_PATH: /mailcatcher
      {%- endif %}
services:   
  app:
    <<: [ *base ]
  setup:
    <<: [ *base ]
  {% if cookiecutter.with_mailcatcher %}
  mailcatcher:
    <<: [ *base ]
    entrypoint:
    - sh
    - -c
    - 'chown mailhog /mails && pw=$$(MH_AUTH_FILE="" MailHog bcrypt "$${MAILCATCHER_PASSWORD:-mailcatcher}")
      && echo "$${MAILCATCHER_USER:-mailcatcher}:$$pw" > $$MH_AUTH_FILE && su mailhog
      -p -c MailHog'
    hostname: mailcatcher
    image: corpusops/mailhog
    networks: {app_net: {ipv4_address: "{{'${'}}{{network}}:-172.38.0}.12"}}
    user: root
    volumes:
    - mails:/mails:rw
  {% endif %}
  {% if cookiecutter.with_db %}
  db:
    <<: [ *base ]
  {% endif %}
volumes:
  mails: {}
