version: "3.8"
{%- set u = cookiecutter.lname.upper() %}
x-images:
  x-restart: &restart
    restart: {{cookiecutter.restart_policy}}
services:
{%- if cookiecutter.with_logging %}
  log:
    # ensure no syslog log loop
    <<: [ *restart ]
    volumes: [logs:/var/log/docker]
{%- endif %}
  app:
    <<: [ *restart ]
{%-  if cookiecutter.with_db %}
  db:
    <<: [ *restart ]
{%- endif %}
  setup:
    <<: [ *restart ]
volumes:
{%- if cookiecutter.with_logging %}
  logs:
{%- endif %}
