version: "3.8"
services:
  app:
    environment:
      NO_NVM_INSTALL: "${NO_NVM_INSTALL-}"
      NO_PIP_INSTALL: "${NO_PIP_INSTALL-}"
    volumes:
    - "./requirements:/w/requirements"
    - "./src:/w/src"
    - "./lib:/w/lib"
    - "${DATA_FOLDER:-./data}:/w/data"
    - "./bin:/w/bin"
    - "./git:/w/.git"
    - "./setup.py:/w/setup.py"
{% if cookiecutter.with_node %}
    - "./node_modules:/w/node_modules"
    - "./.nvmrc:/w/.nvmrc"
{%endif%}
