version: "3.8"
{%- set u = cookiecutter.lname.upper() %}
{%- set network = '{}_NETWORK'.format(u).replace('-', '_') %}
{%- set netpref2 = cookiecutter.network.split('.')[:2]|join('.') %}
{%- set netpref3 = cookiecutter.network.split('.')[:3]|join('.') %}
services:
{%- if cookiecutter.with_logging %}
  log:
    restart: {{cookiecutter.restart_policy}}
{%- endif %}
  app:
    restart: {{cookiecutter.restart_policy}}
  {% if cookiecutter.with_db %}
  db:
    restart: {{cookiecutter.restart_policy}}
  {% endif %}
  setup:
    restart: {{cookiecutter.restart_policy}}
