version: "3.8"
x-images:
  base: &base
    build:
      context: "."
      args:
        PY_VER: "{{cookiecutter.py_ver}}"
        BUILDKIT_INLINE_CACHE: "${BUILDKIT_INLINE_CACHE:-1}"
services:
  app: { <<: [ *base ] }
